#' Synthetic demonstration input matrix
#'
#' A small simulated Perturb-seq differential-expression matrix (120
#' perturbations x 400 genes) with two planted pathway-level relations:
#' PATHWAY_A activates PATHWAY_B and PATHWAY_C suppresses PATHWAY_D (CRISPRi
#' orientation), plus a strong on-target knockdown on every row's own gene.
#' Generated by \code{inst/scripts/make_demo_data.R} (seeded).
#'
#' @format numeric matrix, 120 x 400; rownames = perturbed gene symbols,
#'   colnames = measured gene symbols.
#' @usage data(demo_z)
"demo_z"

#' Synthetic demonstration pathway collection
#'
#' Six disjoint 30-gene pathways over the \code{demo_z} gene vocabulary.
#' Members of PATHWAY_A, PATHWAY_C, and PATHWAY_E are among the perturbed
#' genes; see \code{demo_z}.
#'
#' @format named list of 6 character vectors.
#' @usage data(demo_pathways)
"demo_pathways"
